### ISSUE TITLE
Can't Maximise the application

### ISSUE THREAD

**Issue by ar0ra1** [cjfloss/envelope#32] opened 2018-02-11 06:52 UTC

**Comment by cjfloss** [comment] 2018-02-11 19:23
I can't reproduce the issue.

Needs more information.

**Comment by ar0ra1** [comment] 2018-02-12 05:46
Here : [Video](https://webmshare.com/EVmOy)

>Video will delete in 7 days

**Comment by cjfloss** [comment] 2018-02-13 23:04
Your screen is smaller than 800 pixels which is envelope's window size.
It is fixed now.

Thanks for reporting!!

**Closed** 2018-02-13 23:08 UTC
Labels: bug, minor

**Comment by ar0ra1** [comment] 2018-02-14 02:07
Well 1366x768 is the default resolution for most of the laptops.
